name: Purge Camo Cache

on:
  push:
    branches:
      - main  # Ou o nome da sua branch principal

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Camo Cache
        uses: kevincobain2000/action-camo-purge@v1
